### ISSUE TITLE
Oh Issa!!

### ISSUE THREAD

**Issue by gSpera** [codegiiks/issa#6]
Insieme possiamo farcela
Ohhhhh Issa
![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimg.freepik.com%2Ffoto-gratuito%2Fl-39-uomo-d-39-affari-con-una-corda_1112-390.jpg%3Fsize%3D338%26ext%3Djpg&f=1&nofb=1)

**Comment by pasc4le** [comment]
useless 🤦🏼
